### PR TITLE
OAB publication importer: update publications with existing OA URLs

### LINKED ISSUE #190: OA URL cannot be updated on Admin
The admin UI does not have the ability to update the open access url that is obtained from Open Access Button. In some cases these values are wrong and it would be helpful if the admins could update (or delete) the URL.

### PR DESCRIPTION
**Pull request by nicktiberi**
Closes #190.

The logic for `import_all` has been modified to now query for all publications that have a DOI, regardless of whether they have an open access URL or not. This will have the effect of allowing the OAB publication importer to correct any incorrect URLs that we may have previously received from the OAB API.

### CODE REVIEW

File: app/importers/open_access_button_publication_importer.rb [hunk 1]
```diff
@@ -24,7 +24,7 @@ def import_new
   private
 
   def all_pubs
-    Publication.where.not(doi: nil).where.not(doi: '').where(%{open_access_url IS NULL OR open_access_url = ''})
+    Publication.where.not(doi: nil).where.not(doi: '')
```
Comment (awead) [inline app/importers/open_access_button_publication_importer.rb:27]: @nicktiberi Do the tests break if you put the old sql statement back in? I'm seeing that you changed the tests, but I don't see the underlying test data has changed. I'm wondering if we could get a regression bug here.

**Review by awead — CHANGES_REQUESTED** [review]
Just a question... otherwise, LGTM.

File: app/importers/open_access_button_publication_importer.rb (hunk 1 above)
Comment (nicktiberi) [reply app/importers/open_access_button_publication_importer.rb:27]: Yes, they do. The tests have some code that populates the publication with an open access URL:

```
before { pub.update_attribute(:open_access_url, "existing_url") }
```

With the deleted WHERE clause put back, these tests would fail because `all_pubs` would not include the test publication, since it would have a populated `open_access_url`.

**Review by EricDurante — APPROVED** [review]
looks good
